/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "esdhxkpqyeyvztcigsuk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzZGh4a3BxeWV5dnp0Y2lnc3VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4NTA3ODcsImV4cCI6MjA4ODQyNjc4N30.aqShsBTkETfYzPOhxZ3riFTF4o-AYr-RBBn2B5JQUZo"